name: DiffSinger Demo Pipeline

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'SVS checkpoint name to demo'
        required: true
        default: 'svs_popcs'
  push:
    branches:
      - main
      - ci/demo-pipeline
    tags:
      - 'v*'

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t diffsinger-demo .

      - name: Run inference in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/outputs":/workspace/outputs \
            diffsinger-demo \
            bash -lc "\
              mkdir -p checkpoints && \
              echo 'Downloading checkpoint via HTTP…' && \
              curl -L \
                -o checkpoints/${{ inputs.model }}.pth \
                https://github.com/openvpi/DiffSinger/releases/download/v0.1/${{ inputs.model }}.pth && \
              python inference/svs/inference.py \
                --config configs/svs/popcs/svs.yaml \
                --checkpoint checkpoints/${{ inputs.model }}.pth \
                --output outputs/demo.wav\
            "

      - name: Upload demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-waveform
          path: outputs/demo.wav







